--1번 문제
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;
--2번 문제
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME)!=3 ;

--3번 문제
SELECT PROFESSOR_NAME,TO_CHAR(SYSDATE, 'YYYY') - (1900+(SUBSTR(PROFESSOR_SSN, 0, 2)))
FROM TB_PROFESSOR;


--4번 문제
SELECT SUBSTR(PROFESSOR_NAME,2,3) 이름
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME)!=4 AND LENGTH(PROFESSOR_NAME)!=2;

--5번 문제
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE TO_CHAR(ENTRANCE_DATE, 'YYYY') - (1900+SUBSTR(STUDENT_SSN,1,2))=19
ORDER BY 1 DESC;

--6번 문제
SELECT TO_CHAR(TO_DATE(20201225),'DAY') 요일 FROM DUAL;
--7번 문제
SELECT 
TO_CHAR(TO_DATE('99/10/11','YY/MM/DD'),'YYYY/MM/DD'), --2099
TO_CHAR(TO_DATE('49/10/11','YY/MM/DD'),'YYYY/MM/DD'), -- 2049
TO_CHAR(TO_DATE('99/10/11','RR/MM/DD'),'RRRR/MM/DD'), -- 1999
TO_CHAR(TO_DATE('49/10/11','RR/MM/DD'),'RRRR/MM/DD') -- 2049
FROM DUAL;
--8번 문제

SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,0,1) != 'A';

--9번 문제
SELECT  ROUND(AVG(POINT),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

--10번 문제
SELECT DEPARTMENT_NO AS "학과번호", COUNT(DEPARTMENT_NO) AS "학생수(명)"
FROM TB_STUDENT 
GROUP BY DEPARTMENT_NO
ORDER BY 1;
--11번 문제
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--12번 문제
SELECT SUBSTR(TERM_NO,0,4) 년도, ROUND(AVG(NVL(POINT,0)),1)
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,0,4)
ORDER BY 1;
--13번 문제
SELECT DEPARTMENT_NO, COUNT(ABSENCE_YN)
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N'
GROUP BY DEPARTMENT_NO
ORDER BY 1;
--14번 문제

SELECT STUDENT_NAME, COUNT(STUDENT_NAME)
FROM TB_STUDENT
HAVING COUNT(STUDENT_NAME) != 1
GROUP BY STUDENT_NAME
ORDER BY 1;
--15번 문제
SELECT SUBSTR(TERM_NO,0,4) 년도, SUBSTR(TERM_NO,5,6) 학기 , FLOOR(AVG(NVL(POINT,0))) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,0,4),SUBSTR(TERM_NO,5,6)
ORDER BY 1;
