--1번문제
SELECT EMP_ID,EMP_NAME,DEPT_TITLE,JOB_NAME,HIRE_DATE,ROWNUM 순위, (SALARY*BONUS)*12
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE ROWNUM <=5
ORDER BY (SALARY*BONUS)*12;

SELECT EMP_NAME,(SALARY*BONUS)*12
FROM EMPLOYEE
WHERE BONUS IS NOT NULL;

SELECT EMP_ID,EMP_NAME,DEPT_TITLE,JOB_NAME,HIRE_DATE,ROWNUM 순위
FROM (SELECT 
EMP_NAME,
(SALARY+SALARY*BONUS)*12,
HIRE_DATE,
JOB_NAME,
DEPT_TITLE,
EMP_ID

FROM EMPLOYEE

JOIN JOB USING (JOB_CODE)
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)

WHERE BONUS IS NOT NULL
ORDER BY (SALARY*BONUS)*12 DESC)
WHERE ROWNUM <=5;

--2 
SELECT DEPT_TITLE,SUM(SALARY)
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE)
HAVING SUM(SALARY) > (SELECT SUM(SALARY) * 0.2
                     FROM EMPLOYEE)
GROUP BY DEPT_TITLE;




SELECT SUM(SALARY) * 0.2
FROM EMPLOYEE;

--3
WITH TOPN_SAL AS (
    SELECT SUM(SALARY) "SUM_SALARY", AVG(NVL(SALARY, 0)) "AVG_SALARY"
    FROM EMPLOYEE
    ORDER BY AVG(NVL(SALARY, 0)) DESC
)

    
SELECT SUM_SALARY,AVG_SALARY
FROM TOPN_SAL;